export const hubCopy = {
  kicker: 'Shinkei Systems',
  wordmark: 'Sere',
  subtitle: 'Arcade',
  tagline: 'Two cabinets. One quality bar.',
  careScore: 'Seremoni quality',
  pick: 'Pick a cabinet',
  careName: 'Care',
  careBlurb: 'Six Seconds. Spike, gill, ice.',
  mazeName: 'Catch',
  mazeBlurb: 'Boat, machine, pack. Keep the lot cold.',
  boardName: 'Leaderboard',
  boardBlurb: 'Best quality, best time, this device.',
  playCare: 'Play Care',
  playMaze: 'Play Catch',
  openBoard: 'Open leaderboard',
  hub: 'Hub',
  backHub: 'Hub',
  nav: 'Sere arcade',
  firstScore: 'A new Seremoni quality starts at zero.',
  howTitle: 'How the arcade thinks',
  howMda: [
    'Mechanics: Care is a timing cabinet. Catch is a boat-to-lot run: net, feed, care beat, pack.',
    'Dynamics: misses, a warm hold, and a backed-up bay drain freshness. Clean catch, feed, and pack raise Combo. The clock does not pause once a run starts.',
    'Aesthetics: care and stillness. The prize is a held lot, not a pile of points.',
  ],
  howGamesTitle: 'Cabinets',
  howGames: [
    'Care: hit the brain mark, cut the gill, ice the hold. Craft, Systems, Chain.',
    'Catch: arrows or A D to move. Space nets the school. F feeds the intake. Pack ice, seal, band, or crate on the bay.',
  ],
  howTo: 'How to play',
  howToClose: 'Close how to play',
  emptyBoard: 'No scores on this board yet. Play a run and save initials after a personal best.',
  rank: 'Rank',
  name: 'Name',
  quality: 'Quality',
  time: 'Time',
  level: 'Level',
  date: 'Date',
  copyBoard: 'Copy results',
  copied: 'Copied.',
  copyFail: 'Copy failed. Select the text instead.',
  overall: 'Best Sere run',
  overallLine: (game: string, name: string, score: number, time: string) =>
    `${name}  ${score}  ${time}  ${game}`,
  initialsTitle: 'New best',
  initialsLead: 'Save initials on this device.',
  initialsHint: '3 to 12 letters or numbers.',
  initialsSave: 'Save score',
  initialsSkip: 'Skip',
  initialsLabel: 'Initials or name',
  pauseTitle: 'Paused',
  resume: 'Resume',
  abandon: 'Leave run',
} as const
