export const zineCopy = {
  h1: 'Six seconds.',
  kicker: 'Vol. 01 / Field Brief No. 01',
  byline: 'By David T Phung. Sept 2026.',
  count: (stop: number, total: number) => `${stop} / ${total}`,
  progressLabel: 'Brief progress',
  contents: 'Contents',
  zoom: 'Zoom',
  share: 'Share',
  close: 'Close',
  prev: 'Prev',
  next: 'Next',
  copied: 'Copied.',
  shareTitle: 'Six seconds.',
  shareText: 'Field Brief No. 01',
  linkLabel: 'Brief link',
  chaptersLabel: 'Chapters',
  contentsLabel: 'Contents',
  region: 'Six seconds field brief',
  zoomHint: 'Drag to look across the page.',
  keys: 'Left and right arrows turn the page. Home and End jump to the ends. Escape closes.',
  disclaimer: 'Not affiliated with Shinkei Systems or Seremoni. Non commercial brief.',
  credits: 'Photos: Lobo for Fast Company, Seremoni, Shinkei Systems.',
  announce: (stop: number, total: number, title: string) => `Stop ${stop} of ${total}. ${title}`,
  stopLabel: (title: string, page: string) => `${title}. ${page}`,
} as const
